/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: darwin64-x86_64"
#define DATE "built on: Thu Mar  5 07:59:47 2026 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','c','c',' ','-','f','P',
    'I','C',' ','-','a','r','c','h',' ','x','8','6','_','6','4',' ',
    '-','O','3',' ','-','W','a','l','l',' ','-','D','L','_','E','N',
    'D','I','A','N',' ','-','D','O','P','E','N','S','S','L','_','P',
    'I','C',' ','-','D','_','R','E','E','N','T','R','A','N','T',' ',
    '-','D','O','P','E','N','S','S','L','_','B','U','I','L','D','I',
    'N','G','_','O','P','E','N','S','S','L',' ','-','D','N','D','E',
    'B','U','G',' ','-','I','/','u','s','r','/','l','o','c','a','l',
    '/','o','p','t','/','o','p','e','n','s','s','l','@','1','.','1',
    '/','i','n','c','l','u','d','e',':','-','I','/','u','s','r','/',
    'l','o','c','a','l','/','o','p','t','/','l','i','b','i','m','o',
    'b','i','l','e','d','e','v','i','c','e','/','i','n','c','l','u',
    'd','e',' ','-','I','/','u','s','r','/','l','o','c','a','l','/',
    'o','p','t','/','l','i','b','i','r','e','c','o','v','e','r','y',
    '/','i','n','c','l','u','d','e',' ','-','I','/','u','s','r','/',
    'l','o','c','a','l','/','o','p','t','/','l','i','b','p','l','i',
    's','t','/','i','n','c','l','u','d','e',' ','-','I','/','u','s',
    'r','/','l','o','c','a','l','/','o','p','t','/','l','i','b','z',
    'i','p','/','i','n','c','l','u','d','e',' ','-','I','/','u','s',
    'r','/','l','o','c','a','l','/','o','p','t','/','c','u','r','l',
    '/','i','n','c','l','u','d','e',' ','-','I','/','u','s','r','/',
    'l','o','c','a','l','/','o','p','t','/','o','p','e','n','s','s',
    'l','@','3','/','i','n','c','l','u','d','e',' ','-','I','/','u',
    's','r','/','l','o','c','a','l','/','o','p','t','/','l','i','b',
    'u','s','b','m','u','x','d','/','i','n','c','l','u','d','e',' ',
    '-','I','/','u','s','r','/','l','o','c','a','l','/','o','p','t',
    '/','l','i','b','x','m','l','2','/','i','n','c','l','u','d','e',
    ' ','-','I','/','u','s','r','/','l','o','c','a','l','/','o','p',
    't','/','z','l','i','b','/','i','n','c','l','u','d','e','\0'
};
